const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync('index.html','utf8'),runtime=fs.readFileSync('i18n.js','utf8'),catalog=JSON.parse(fs.readFileSync('translations-en.json','utf8'));
function setup(saved){const dom=new JSDOM(html,{url:'https://manobras.asf.surf/',runScripts:'outside-only'});const w=dom.window;Object.defineProperty(w.navigator,'language',{value:'en-US'});w.localStorage.setItem('asf_xp','100');w.localStorage.setItem('asf_manobras',JSON.stringify({'Bottom turn':true}));if(saved)w.localStorage.setItem('asf-language',saved);for(const s of w.document.querySelectorAll('script:not([src])')){if(s.type!=='application/ld+json'&&s.textContent.includes('const FOCOS=')){w.eval(s.textContent+'\nwindow.__focusForTest=FOCOS;');}}w.eval(runtime);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));return dom;}
function close(dom){dom.window.close();}
test('English browser still starts in Portuguese with no saved choice',()=>{const dom=setup();assert.equal(dom.window.document.documentElement.lang,'pt-BR');assert.equal(dom.window.localStorage.getItem('asf-language'),null);assert.ok(dom.window.document.querySelector('#asf-language-control'));close(dom);});
test('All static learning text has reviewed English coverage or is an unchanged surf term or brand',()=>{const dom=setup(),d=dom.window.document;const unchanged=new Set(['⚡ ASF Manobras','ASF Treino','ASF Pop-up','↗️ Cutback:','🚀 Floater:','cutback, floater','ASF Ranking','ASF App','ASF — Associação de Surf Feminino ·','hub','asf-app','Cookies']);const tree=d.createTreeWalker(d.body,dom.window.NodeFilter.SHOW_TEXT),nodes=[];let n;while(n=tree.nextNode()){if(n.parentElement.closest('script,style,#asf-language-control,#tr,#fc-t,#fc-d,#fc-em'))continue;const text=n.nodeValue.trim();if(!/\p{L}/u.test(text)||unchanged.has(text)||text.includes('XP:'))continue;nodes.push([n,n.nodeValue]);}dom.window.ASF_I18N.setLanguage('en');const misses=nodes.filter(([node,original])=>node.nodeValue===original&&/\p{L}/u.test(original)).map(([,text])=>text.trim());assert.deepEqual(misses,[]);close(dom);});
test('Full Cutback guide switches reversibly without XP, keys, anchors or link changes',()=>{const dom=setup(),w=dom.window,d=w.document;const xp=w.localStorage.getItem('asf_xp'),state=w.localStorage.getItem('asf_manobras'),guide=d.querySelector('#guia-cutback-completo'),original=guide.textContent,links=[...d.querySelectorAll('a')].map(a=>a.href);w.setLanguage('en');assert.match(guide.textContent,/The perfect cutback/);assert.match(guide.textContent,/Common mistakes/);assert.match(guide.textContent,/Dry-land exercise/);assert.match(d.querySelector('#tr').textContent,/Whitewater takeoff/);assert.equal(w.localStorage.getItem('asf_xp'),xp);assert.equal(w.localStorage.getItem('asf_manobras'),state);assert.deepEqual([...d.querySelectorAll('a')].map(a=>a.href),links);w.setLanguage('pt-BR');assert.equal(guide.textContent,original);assert.equal(w.localStorage.getItem('asf_xp'),xp);close(dom);});
test('Saved English is restored, and original Cutback checkbox still earns exactly 20 XP',async()=>{const dom=setup('en'),w=dom.window,d=w.document;assert.equal(d.documentElement.lang,'en');const input=[...d.querySelectorAll('#tr input')].find(el=>el.getAttribute('onchange').includes("'Cutback'"));assert.ok(input);w.tgl('Cutback',true,20);await new Promise(r=>w.setTimeout(r,5));assert.equal(w.localStorage.getItem('asf_xp'),'120');assert.equal(JSON.parse(w.localStorage.getItem('asf_manobras')).Cutback,true);assert.equal(JSON.parse(w.localStorage.getItem('asf_manobras'))['Bottom turn'],true);w.setLanguage('pt-BR');w.setLanguage('en');assert.equal(w.localStorage.getItem('asf_xp'),'120');assert.ok([...d.querySelectorAll('#tr input')].find(el=>el.getAttribute('onchange').includes("'Cutback'")).checked);close(dom);});
test('All eight rotating focuses and all five countdowns translate',async()=>{const dom=setup('en'),w=dom.window,d=w.document;assert.equal(w.__focusForTest.length,8);for(const focus of w.__focusForTest){assert.ok(catalog[focus.t]);assert.ok(catalog[focus.d]);d.querySelector('#fc-t').textContent=focus.t;d.querySelector('#fc-d').textContent=focus.d;await new Promise(r=>w.setTimeout(r,2));assert.equal(d.querySelector('#fc-t').textContent,catalog[focus.t]);assert.equal(d.querySelector('#fc-d').textContent,catalog[focus.d]);}for(let days=1;days<=5;days++){const pt='🔄 Novo foco em '+days+(days===1?' dia':' dias');d.querySelector('#fc-em').textContent=pt;await new Promise(r=>w.setTimeout(r,2));assert.equal(d.querySelector('#fc-em').textContent,catalog[pt]);}close(dom);});
